name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      build_from:
        description: |
          Branch or tag to build release artifacts from.
        required: false
      release_as:
        description: |
          Publish release under this tag, or update release assets if such release exists.
          If empty, release publishing will be skipped.
        required: false

env:
  package_name: "greptimedb-ingester-erlnif"
  package_pretty_name: "GreptimeDB Ingester Erlang NIF"

jobs:
  mac:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - "28.2-2"
        rebar3:
          - "3.24.0"
        os:
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: emqx/macos-erlang@f744c98139c0db83a10619587d4bae4fc49765a8 # v1.0.0
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.inputs.build_from }}

      - name: build
        run: env BUILD_RELEASE=1 make

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ env.package_name }}-${{ matrix.os }}-${{ matrix.otp }}
          path: |
            _packages/*.gz
            _packages/*.gz.sha256
          retention-days: 7

  linux:
    strategy:
      fail-fast: false
      matrix:
        erlang:
          - otp: "28.2-2"
            elixir: "1.19.1"
            builder: "6.0-9"
        arch:
          - amd64
          - arm64
        os:
          - ubuntu24.04
          - ubuntu22.04
          - debian13
          - debian12
          - debian11
          - el9
          - el8
          - amzn2023

    runs-on: ${{ github.repository_owner == 'emqx' && format('aws-{0}', matrix.arch) || (matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04') }}

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.inputs.build_from }}
          submodules: recursive
        # NOTE: build in container does not work because older platforms like
        #       el7 and amzn2 do not support nodejs 20 runtime which is required
        #       for github actions
      - name: build
        env:
          IMAGE: ghcr.io/emqx/emqx-builder/${{ matrix.erlang.builder }}:${{ matrix.erlang.elixir }}-${{ matrix.erlang.otp }}-${{ matrix.os }}
        run: >-
          docker run --rm -v ${PWD}:/wd ${IMAGE} bash -euc "
          git config --global --add safe.directory '*';
          make -C /wd BUILD_RELEASE=1
          "

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ env.package_name }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.erlang.otp }}
          path: |
            _packages/*.gz
            _packages/*.gz.sha256
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    if: github.event.inputs.release_as || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    needs:
      - mac
      - linux
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          pattern: ${{ env.package_name }}-*
          path: packages
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          name: ${{ env.package_pretty_name }} ${{ github.event.inputs.release_as || github.ref_name }} Released
          tag_name: ${{ github.event.inputs.release_as || github.ref_name }}
          files: packages/*
          draft: false
          prerelease: false
